### ISSUE TITLE
Doesn't compile on Windows (expected error union type)

### ISSUE THREAD

**Issue by michaelowens** [Hejsil/zig-clap#65]
I'm new to Zig and in the trying out phase so I don't feel comfortable making a PR, but couldn't get this to compile in my project. I have added the project as a submodule and running Windows 11 + zig 0.9.0, but when trying example code I'm getting:

```shell
.\libs\zig-clap\clap\args.zig:76:39: error: expected error union type, found '?std.process.NextError![:0]u8'
            return (try iter.args.next(iter.arena.allocator())) orelse return null;
                                      ^
.\libs\zig-clap\clap\args.zig:76:21: note: referenced here
            return (try iter.args.next(iter.arena.allocator())) orelse return null;
```

After some tinkering I noticed that I can get it to compile by removing the brackets around the `try` in the failing function:

```patch
diff --git a/clap/args.zig b/clap/args.zig
index 90c50fa..16299c8 100644
--- a/clap/args.zig
+++ b/clap/args.zig
@@ -73,7 +73,7 @@ pub const OsIterator = struct {

     pub fn next(iter: *OsIterator) Error!?[:0]const u8 {
         if (builtin.os.tag == .windows) {
-            return (try iter.args.next(iter.arena.allocator())) orelse return null;
+            return try iter.args.next(iter.arena.allocator()) orelse return null;
         } else {
             return iter.args.nextPosix();
         }
```

**Comment by Hejsil** [comment]
Hi. The zig-clap master branch follows zig master, where this compiles. For a version that works with zig 0.9 have a look at zig-clap 0.5

**Comment by michaelowens** [comment]
Oh, I see! I figured I'd use a package manager for once to install it and I guess that bit me in the ass. Thanks for the reply, I just updated to the master release instead.
